[pytest]
addopts = --reportportal

rp_endpoint = https://reportportal.epam.com
#rp_endpoint = https://reportportal.epam.com/api/v1

rp_api_key = uladzislau-yatsko-personal_AdqfC-T3Td6TKUSTxoe0vaYFE9yIV-Y8UMj47nQcS4osfNM6H1fdEoCVAGpBfrA8

rp_project = uladzislau_yatsko_personal

rp_launch = Pytest_Launch

rp_enable = true